AIA_Tranning/Controllers/LeaveTypesController.cs
using AIA_Tranning.Common;
using AIA_Tranning.Data;
using AIA_Tranning.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace AIA_Tranning.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypesService _service;

        public LeaveTypesController(ILeaveTypesService service) {
            _service = service;
        }

        [Authorize]
        // GET: LeaveTypesController
        public ActionResult Index()
        {
            List<LeaveType> leaveTypes = _service.getAll().ToList();
            return View(leaveTypes);
        }

        // GET: LeaveTypesController/Details/5
        public ActionResult Details(int id)
        {
            bool isExist = _service.isExist(id);
            if (!isExist)
            {
                return NotFound();
            }

            LeaveType leaveType = _service.getById(id);
            return View(leaveType);
        }

        // GET: LeaveTypesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypesController/Create    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LeaveType collection)
        {
            try
            {
                if (!ModelState.IsValid) {
                    return View(collection);
                }

                bool isSuccess = _service.create(collection);

                if (!isSuccess) {
                    ModelState.AddModelError(AIAConstant.ERROR, AIAMessage.ERROR);
                    return View(collection);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeaveTypesController/Edit/5
        public ActionResult Edit(int id)
        {
            bool isExist = _service.isExist(id);
            if (!isExist) {
                return NotFound();
            }

            LeaveType leaveType = _service.getById(id);
            return View(leaveType);
        }

        // POST: LeaveTypesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, LeaveType collection)
        {
            try
            {
                bool isExist = _service.isExist(id);
                if (!isExist)
                {
                    return NotFound();
                }

                bool isSuccess = _service.update(collection);

                if (!isSuccess) {
                    // Show error and rollback
                    ModelState.AddModelError(AIAConstant.ERROR, AIAMessage.ERROR);
                    return View(collection);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(collection);
            }
        }

        // GET: LeaveTypesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeaveTypesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, LeaveType collection)
        {
            try
            {
                bool isExist = _service.isExist(id);
                if (!isExist)
                {
                    return NotFound();
                }

                bool isSuccess = _service.delete(collection);
                if (!isSuccess) {
                    ModelState.AddModelError(AIAConstant.ERROR, AIAMessage.ERROR);
                    return View(collection);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AIA_Tranning/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using AIA_Tranning.Common
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AIA Tranning ASP.Net Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AIA_Tranning</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole(UserRoles.Admin))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item text-dark" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a>
                                        <a class="dropdown-item text-dark" asp-controller="LeaveTypes" asp-action="Index">Leave Allocations</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AIA_Tranning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>